In [1]:
# Imports and dependencies
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as stats
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func
suicide_data = pd.read_csv('resources/master.csv')

In [2]:
suicide_data

,country,year,sex,age,suicides_no,population,suicides_per_100k_pop,gdp_for_year_USD,gdp_per_capita_USD,generation,suicide_tier
0,Albania,1987,male,15-24 years,21,312900,6.71,2.156625e+09,796,Generation X,0
1,Albania,1987,male,35-54 years,16,308000,5.19,2.156625e+09,796,Silent,0
2,Albania,1987,female,15-24 years,14,289700,4.83,2.156625e+09,796,Generation X,0
3,Albania,1987,male,75+ years,1,21800,4.59,2.156625e+09,796,G.I. Generation,0
4,Albania,1987,male,25-34 years,9,274300,3.28,2.156625e+09,796,Boomers,0
...,...,...,...,...,...,...,...,...,...,...,...
27815,Uzbekistan,2014,female,35-54 years,107,3620833,2.96,6.306708e+10,2309,Generation X,0
27816,Uzbekistan,2014,female,75+ years,9,348465,2.58,6.306708e+10,2309,Silent,0
27817,Uzbekistan,2014,male,5-14 years,60,2762158,2.17,6.306708e+10,2309,Generation Z,0
27818,Uzbekistan,2014,female,5-14 years,44,2631600,1.67,6.306708e+10,2309,Generation Z,0
27819,Uzbekistan,2014,female,55-74 years,21,1438935,1.46,6.306708e+10,2309,Boomers,0

In [3]:
suicide_data_df = suicide_data
suicide_data_df = suicide_data_df.dropna(how='any')
suicide_data_df

,country,year,sex,age,suicides_no,population,suicides_per_100k_pop,gdp_for_year_USD,gdp_per_capita_USD,generation,suicide_tier
0,Albania,1987,male,15-24 years,21,312900,6.71,2.156625e+09,796,Generation X,0
1,Albania,1987,male,35-54 years,16,308000,5.19,2.156625e+09,796,Silent,0
2,Albania,1987,female,15-24 years,14,289700,4.83,2.156625e+09,796,Generation X,0
3,Albania,1987,male,75+ years,1,21800,4.59,2.156625e+09,796,G.I. Generation,0
4,Albania,1987,male,25-34 years,9,274300,3.28,2.156625e+09,796,Boomers,0
...,...,...,...,...,...,...,...,...,...,...,...
27815,Uzbekistan,2014,female,35-54 years,107,3620833,2.96,6.306708e+10,2309,Generation X,0
27816,Uzbekistan,2014,female,75+ years,9,348465,2.58,6.306708e+10,2309,Silent,0
27817,Uzbekistan,2014,male,5-14 years,60,2762158,2.17,6.306708e+10,2309,Generation Z,0
27818,Uzbekistan,2014,female,5-14 years,44,2631600,1.67,6.306708e+10,2309,Generation Z,0
27819,Uzbekistan,2014,female,55-74 years,21,1438935,1.46,6.306708e+10,2309,Boomers,0

In [4]:
## Exporting dataframes as CSVs to then use in database loading
suicide_data_df.to_csv("output/suicides.csv", index=False)

In [5]:
## Define and run engine for database loading
engine = create_engine(f"sqlite:///data/suicides.sqlite")
Base = automap_base()
Base.prepare(autoload_with=engine)
session = Session(engine)
connection = engine.connect()

In [6]:
## Load dataframes into database
suicide_data_df.to_sql("suicides", connection, if_exists="replace")

27820